# Generated by Django 2.0.2 on 2018-02-27 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('loc_office', models.CharField(max_length=100)),
                ('loc_parking', models.CharField(max_length=100)),
                ('car_year', models.IntegerField(default=2010)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDriver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_over_21', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address_street', models.CharField(max_length=100)),
                ('address_gps_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('address_gps_lng', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_car_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_service_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_shop_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name_first',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name_last',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
