# Generated by Django 2.0.2 on 2018-02-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180227_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_year', models.IntegerField(default=2010)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=100)),
                ('loc_parking', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='car_year',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='loc_parking',
        ),
        migrations.AddField(
            model_name='shopowner',
            name='shop_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.CarOwner'),
        ),
    ]
