# Generated by Django 2.0.2 on 2018-03-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180301_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_model_trim',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
