# Generated by Django 2.0.2 on 2018-03-02 15:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
