# Generated by Django 2.0.2 on 2018-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180228_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedriver',
            name='is_gpa_good',
            field=models.BooleanField(default=False),
        ),
    ]
