# Generated by Django 2.0.2 on 2018-03-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_shopowner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
