# Generated by Django 2.0.2 on 2018-02-28 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_servicedriver_is_gpa_good'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedriver',
            old_name='is_gpa_good',
            new_name='is_gpa_over3',
        ),
    ]
