# Generated by Django 2.0.2 on 2018-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180301_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='address_gps_lat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopowner',
            name='address_gps_lng',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
